### ISSUE TITLE
testing 3

### ISSUE THREAD

**Issue by block-spider** [block-spider/block#13]
@testtip @tea-spoon

**Comment by testtip** [comment]
@tea-spoon, you've [been sent](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4y7yny4xp3c5skpg0y7mu5hwgp9q0mlprleq) `0.0003 BCH`| `~   0.38 USD` by @block-spider. Please [claim it!](http://www.chaintip.org/#claim)

**Comment by block-spider** [comment]
@testtip @tea-spoon

**Comment by testtip** [comment]
@tea-spoon, you've [been sent](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld49swqyfn9hjexhmm0gyxxu768cjghymllepy) `0.0003 BCH`| `~   0.38 USD` by @block-spider. Please [claim it!](http://www.chaintip.org/#claim)

**Comment by block-spider** [comment]
@testtip @tea-spoon

**Comment by block-spider** [comment]
bling @tea-spoon @testtip 4 days
