### ISSUE TITLE
ok lets go

### ISSUE THREAD

**Issue by block-spider** [block-spider/block#14]
this is an issue @tea-spoon #12

**Comment by tea-spoon** [comment]
oh nice issue you got there @testtip 3 days

**Comment by testtip** [comment]
`0.0003 BCH`| `~   0.38 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld49gfcz30yw576l9g5rmxht9hwlx5d98ay34g) to this issue by @tea-spoon. Claim this bounty by getting a PR merged that fixes this issue.

**Comment by tea-spoon** [comment]
oh nice issue you got there @testtip 3 days

**Comment by testtip** [comment]
`0.0003 BCH`| `~   0.38 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4rjr2lf3dmc3f2gdgj8n59ghek3qfwk3yxes) to this issue by @tea-spoon. Claim this bounty by getting a PR merged that fixes this issue.

**Comment by block-spider** [comment]
@testtip 4 days

**Comment by block-spider** [comment]
@testtip

**Comment by testtip** [comment]
`0.0003 BCH`| `~   0.37 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld40un3t80jqeyzylw7mu9vsl5a5cgqhlczw9s) to this issue by @block-spider.
Claim this bounty by getting a pull request merged that fixes this issue.

**Comment by testtip** [comment]
`0.0003 BCH`| `~   0.37 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld40un3t80jqeyzylw7mu9vsl5a5cgqhlczw9s) to this issue by @block-spider.
Claim this bounty by getting a pull request merged that fixes this issue.

**Comment by testtip** [comment]
`0.0003 BCH`| `~   0.37 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld40un3t80jqeyzylw7mu9vsl5a5cgqhlczw9s) to this issue by @block-spider.
Claim this bounty by getting a pull request merged that fixes this issue.

**Comment by testtip** [comment]
`0.0003 BCH`| `~   0.37 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld40un3t80jqeyzylw7mu9vsl5a5cgqhlczw9s) to this issue by @block-spider.
Claim this bounty by getting a pull request merged that fixes this issue.

**Comment by testtip** [comment]
`0.0003 BCH`| `~   0.37 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld40un3t80jqeyzylw7mu9vsl5a5cgqhlczw9s) to this issue by @block-spider.
Claim this bounty by getting a pull request merged that fixes this issue.

**Comment by block-spider** [comment]
@testtip

**Comment by block-spider** [comment]
@testtip
