### ISSUE TITLE
Issue Title

### ISSUE THREAD

**Issue by block-spider** [block-spider/block#15]
Issue Body

**Comment by tea-spoon** [comment]
@testtip

**Comment by testtip** [comment]
`0.0003 BCH`| `~   0.37 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld42h0nwkuxcffel9gd4xl9rtvmd7ux3nnsx4e) to this issue by @tea-spoon.
Claim [this bounty](http://github.chaintip.org/testtip/bounties/issues/5) by getting a pull request merged that fixes this issue.

**Comment by testtip** [comment]
Thank you @tea-spoon! `0.0006 BCH`| `~   0.74 USD` has now been tipped to this issue.
Claim [this bounty](http://github.chaintip.org/testtip/bounties/issues/5) by getting a pull request merged that fixes this issue.

**Comment by tea-spoon** [comment]
@testtip 4 days

**Comment by testtip** [comment]
Thank you @tea-spoon! `0.0009 BCH`| `~   1.12 USD` has now been tipped to this issue.
Claim [this bounty](http://github.chaintip.org/testtip/bounties/issues/5) by getting a pull request merged that fixes this issue.

**Comment by block-spider** [comment]
@testtip

**Comment by testtip** [comment]
Thank you @block-spider! `0.0006 BCH`| `~   0.74 USD` has now been tipped to this issue.
Claim [this bounty](http://github.chaintip.org/testtip/bounties/issues/5) by getting a pull request merged that fixes this issue.

**Comment by testtip** [comment]
Thank you @block-spider! `0.0006 BCH`| `~   0.74 USD` has now been tipped to this issue.
Claim [this bounty](http://github.chaintip.org/testtip/bounties/issues/5) by getting a pull request merged that fixes this issue.

**Comment by tea-spoon** [comment]
@testtip
