### ISSUE TITLE
yeye

### ISSUE THREAD

**Issue by block-spider** [block-spider/block#6]
eye

**Comment by block-spider** [comment]
@testtip @tea-spoon blahaha

**Comment by block-spider** [comment]
@testtip @tea-spoon blahaha

**Comment by block-spider** [comment]
@testtip @tea-spoon blahaha sdafadsf

**Comment by block-spider** [comment]
hello

**Comment by block-spider** [comment]
@testtip @tea-spoon blah

**Comment by block-spider** [comment]
@testtip @tea-spoon blahsdaflkhj

**Comment by block-spider** [comment]
@testtip @tea-spoon blahsdaflkhjasdf

**Comment by block-spider** [comment]
@testtip @tea-spoon blahsdaflkhjasdfkjdh

**Comment by block-spider** [comment]
@testtip @tea-spoon bling

**Comment by block-spider** [comment]
@testtip @tea-spoon bong one

**Comment by block-spider** [comment]
@testtip @tea-spoon bong one two hh

**Comment by block-spider** [comment]
@testtip @tea-spoon bong one two hhsdf

**Comment by block-spider** [comment]
helo

**Comment by block-spider** [comment]
helo

**Comment by block-spider** [comment]
below

**Comment by block-spider** [comment]
heya

**Comment by block-spider** [comment]
hello

**Comment by block-spider** [comment]
weird

**Comment by block-spider** [comment]
test

**Comment by block-spider** [comment]
bling

**Comment by block-spider** [comment]
blah

**Comment by block-spider** [comment]
hello

**Comment by block-spider** [comment]
@testtip @tea-spoon bong one two hhsdf

**Comment by block-spider** [comment]
@testtip @tea-spoon bong one two hhsdfsfdasdf asldfkj

**Comment by block-spider** [comment]
hhh

**Comment by block-spider** [comment]
@testtip hello

**Comment by block-spider** [comment]
sdlfkj

**Comment by block-spider** [comment]
@testtip heheh

**Comment by block-spider** [comment]
they

**Comment by tea-spoon** [comment]
asdf

**Comment by tea-spoon** [comment]
yello

**Comment by block-spider** [comment]
hheye

**Comment by block-spider** [comment]
@testtip heheh

**Comment by block-spider** [comment]
@testtip @tea-spoon bong one two hhsdf hdd

**Comment by block-spider** [comment]
@testtip @tea-spoon blahahsdfsdkj

**Comment by block-spider** [comment]
@testtip @tea-spoon blahaha bhhd

**Comment by testtip** [comment]
@tea-spoon, you've [been sent](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4tmunn7d86dk0x9vxfkp3uvhmz0yzl6dg2xv) `0.0003 BCH`| `~   0.38 USD` by @block-spider. Please [claim it!](http://www.chaintip.org/#claim)

**Comment by tea-spoon** [comment]
@testtip @block-spider

**Comment by testtip** [comment]
@block-spider, you've [been sent](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld40k0ayu9yh0dluch99t99lc2d7qy9pwrc3z9) `0.0003 BCH`| `~   0.38 USD` by @tea-spoon. Please [claim it!](http://www.chaintip.org/#claim)
